import { Lesson } from '../types';

export const HERO_CURRICULUM: Lesson[] = [
    // --- TIER 1: FOUNDATION (Lessons 1-10) ---
    {
        id: 1,
        title: "Home Row Anchors",
        phase: 1,
        description: "Meet your home row anchors: F and J.",
        keys: ['f', 'j'],
        content: "f j f j ff jj fjf jfj f j f j ff jj",
        tips: ["Feel the bumps on F and J – your index fingers live here!", "Keep your fingers curved like you're holding a tennis ball."],
        passingCriteria: { accuracy: 100, wpm: 5 },
        difficulty: 1,
        target_wpm: 10
    },
    {
        id: 2,
        title: "Inner Home Row",
        phase: 1,
        description: "Adding D and K to your anchors.",
        keys: ['d', 'k'],
        content: "fd jk df kj fdd jkk dkf jdf f d k j",
        tips: ["D is for your left middle finger.", "K is for your right middle finger."],
        passingCriteria: { accuracy: 100, wpm: 8 },
        difficulty: 1,
        target_wpm: 12
    },
    {
        id: 3,
        title: "The Ring Reach",
        phase: 1,
        description: "Introducing S and L.",
        keys: ['s', 'l'],
        content: "fs dj kl sl sk dl sss lll sls dld s l s l",
        tips: ["Use your ring fingers for S and L.", "Don't look at the keyboard – trust the bumps!"],
        passingCriteria: { accuracy: 98, wpm: 10 },
        difficulty: 2,
        target_wpm: 15
    },
    {
        id: 4,
        title: "Pinky Power",
        phase: 1,
        description: "The home row is complete with A and ;.",
        keys: ['a', ';'],
        content: "asdf jkl; a; a; ds; fl a;s l;d fjk a ; a ;",
        tips: ["Your pinkies are small but mighty!", "Rest your palms lightly or keep them slightly elevated."],
        passingCriteria: { accuracy: 98, wpm: 12 },
        difficulty: 2,
        target_wpm: 18
    },
    {
        id: 5,
        title: "Rhythm & Flow",
        phase: 1,
        description: "Combining everything on the home row.",
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        content: "asdf jkl; fdsa ;lkj dads lads asks fall a s d f j k l ;",
        tips: ["Focus on rhythm, not speed.", "Accuracy first, speed will follow naturally."],
        passingCriteria: { accuracy: 98, wpm: 15 },
        difficulty: 2,
        target_wpm: 20
    },
    {
        id: 6,
        title: "Word Rhythm I",
        phase: 1,
        description: "Short common words found only on the home row.",
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        content: "sad dad lad add flask salad alfalfa dads lads",
        tips: ["Try to maintain a steady beat.", "Your fingers should always return to the anchor points."],
        passingCriteria: { accuracy: 99, wpm: 18 },
        difficulty: 3,
        target_wpm: 22
    },
    {
        id: 7,
        title: "The Thumb Jump",
        phase: 1,
        description: "Mastering the Spacebar with your thumbs.",
        keys: [' '],
        content: "f f f j j j d d d k k k s s s l l l a a a ; ; ;",
        tips: ["Use either thumb for the spacebar.", "Don't pause too long between words."],
        passingCriteria: { accuracy: 100, wpm: 20 },
        difficulty: 3,
        target_wpm: 25
    },
    {
        id: 8,
        title: "Middle Reach: E & I",
        phase: 1,
        description: "Reaching up to the top row.",
        keys: ['e', 'i'],
        content: "de ki ed ik died eke side lake kid slide desk mask",
        tips: ["Left middle for E, Right middle for I.", "Keep the movement minimal."],
        passingCriteria: { accuracy: 98, wpm: 15 },
        difficulty: 3,
        target_wpm: 20
    },
    {
        id: 9,
        title: "Index Reach: R & U",
        phase: 1,
        description: "Index fingers reaching for R and U.",
        keys: ['r', 'u'],
        content: "fr ju rf uj fur rude red user sure rust dusk rude",
        tips: ["Reach up from F and J.", "Quick snap back to the home row."],
        passingCriteria: { accuracy: 98, wpm: 18 },
        difficulty: 3,
        target_wpm: 22
    },
    {
        id: 10,
        title: "Foundation Test",
        phase: 1,
        description: "Benchmark your Tier 1 progress.",
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';', 'e', 'i', 'r', 'u'],
        content: "the red desk is side user side dark lake fire",
        tips: ["Relax your shoulders.", "Maintain 98%+ accuracy for progression."],
        passingCriteria: { accuracy: 98, wpm: 20 },
        difficulty: 4,
        target_wpm: 30
    },

    // --- TIER 2: SPEED DEVELOPMENT (Lessons 11-25) ---
    {
        id: 11,
        title: "Digraph: TH",
        phase: 2,
        description: "Mastering the most common combination: T and H.",
        keys: ['t', 'h'],
        content: "the that they then there bath with truth",
        tips: ["Think of TH as a single, fluid motion.", "Keep your rhythm steady."],
        passingCriteria: { accuracy: 98, wpm: 25 },
        difficulty: 4,
        target_wpm: 35
    },
    {
        id: 12,
        title: "Digraph: HE",
        phase: 2,
        description: "H and E reach for speed.",
        keys: ['h', 'e'],
        content: "he her here head heart help held",
        tips: ["Your right index (H) to left middle (E).", "Alternate hand balance is key here."],
        passingCriteria: { accuracy: 98, wpm: 25 },
        difficulty: 4,
        target_wpm: 35
    },
    {
        id: 13,
        title: "Digraph: IN",
        phase: 2,
        description: "Right hand focus: I and N.",
        keys: ['i', 'n'],
        content: "in into inside win spin skin thin find",
        tips: ["Middle finger (I) to index finger (N).", "A small, tight vertical movement."],
        passingCriteria: { accuracy: 98, wpm: 28 },
        difficulty: 4,
        target_wpm: 38
    },
    {
        id: 14,
        title: "The 'ING' Suite",
        phase: 2,
        description: "Mastering the high-speed suffix.",
        keys: ['i', 'n', 'g'],
        content: "ing sing song thing long king wing ring swing",
        tips: ["Think of 'ing' as a single musical chord.", "Your right hand does most of the work here."],
        passingCriteria: { accuracy: 98, wpm: 30 },
        difficulty: 5,
        target_wpm: 40
    },
    {
        id: 15,
        title: "Double Vowels: EE & OO",
        phase: 2,
        description: "Rhythmic double taps for common vowels.",
        keys: ['e', 'o'],
        content: "see tree free keep moon soon food door",
        tips: ["Don't rush the double tap.", "Keep your fingers bouncy."],
        passingCriteria: { accuracy: 100, wpm: 30 },
        difficulty: 5,
        target_wpm: 40
    },
    {
        id: 16,
        title: "Double Consonants: LL & SS",
        phase: 2,
        description: "Rhythmic double taps for consonants.",
        keys: ['l', 's'],
        content: "fall hill call tell less pass loss glass",
        tips: ["Ring finger (L) and (S) agility drill.", "Maintain accuracy above all."],
        passingCriteria: { accuracy: 100, wpm: 30 },
        difficulty: 5,
        target_wpm: 40
    },
    {
        id: 17,
        title: "High Frequency: 1-10",
        phase: 2,
        description: "The top 10 most common English words.",
        keys: [],
        content: "the be of and a to in he have it",
        tips: ["These 10 words make up 25% of all English text.", "Type them until they feel automatic."],
        passingCriteria: { accuracy: 99, wpm: 35 },
        difficulty: 6,
        target_wpm: 45
    },
    {
        id: 18,
        title: "High Frequency: 11-20",
        phase: 2,
        description: "Common building blocks.",
        keys: [],
        content: "i for not on with he as you do at",
        tips: ["Focus on the transitions between small words.", "Keep your hands relaxed."],
        passingCriteria: { accuracy: 99, wpm: 35 },
        difficulty: 6,
        target_wpm: 45
    },
    {
        id: 19,
        title: "High Frequency: 21-30",
        phase: 2,
        description: "Common building blocks continued.",
        keys: [],
        content: "this but his by from they we say her she",
        tips: ["Notice the mix of home, top, and bottom row letters.", "Stay centered."],
        passingCriteria: { accuracy: 99, wpm: 38 },
        difficulty: 6,
        target_wpm: 50
    },
    {
        id: 20,
        title: "Speed Sprint I",
        phase: 2,
        description: "Push your limits on common words.",
        keys: [],
        content: "the and for with this that have from they that",
        tips: ["raw twitch speed focus.", "Don't blink!"],
        passingCriteria: { accuracy: 95, wpm: 45 },
        difficulty: 7,
        target_wpm: 55
    },
    {
        id: 21,
        title: "Stretch: T & Y",
        phase: 2,
        description: "Internal index stretches.",
        keys: ['t', 'y'],
        content: "ft jy tf yj try toy that they stayed year",
        tips: ["Diagonal stretch from the home row.", "Minimize hand movement."],
        passingCriteria: { accuracy: 98, wpm: 30 },
        difficulty: 7,
        target_wpm: 40
    },
    {
        id: 22,
        title: "Reach: C & M",
        phase: 2,
        description: "Reaching down with middle fingers.",
        keys: ['c', 'm'],
        content: "dc km cd mk come mica came mice make music",
        tips: ["C is left middle, M is right middle.", "Curl your fingers slightly more."],
        passingCriteria: { accuracy: 97, wpm: 32 },
        difficulty: 7,
        target_wpm: 42
    },
    {
        id: 23,
        title: "Reach: V & N",
        phase: 2,
        description: "Reaching down with index fingers.",
        keys: ['v', 'n'],
        content: "fv jn vf nj van vine never view vein navy",
        tips: ["V and N are directly below F and J.", "Trust your muscle memory."],
        passingCriteria: { accuracy: 97, wpm: 35 },
        difficulty: 7,
        target_wpm: 45
    },
    {
        id: 24,
        title: "Punctuation: , & .",
        phase: 2,
        description: "The breath of the text.",
        keys: [',', '.'],
        content: "I. We, They. Run, fast. Stop. Wait, listen.",
        tips: ["Comma is under K, Period is under L.", "Follow with a single space."],
        passingCriteria: { accuracy: 98, wpm: 30 },
        difficulty: 8,
        target_wpm: 40
    },
    {
        id: 25,
        title: "Tier 2 Graduation",
        phase: 2,
        description: "Benchmark your Speed Development.",
        keys: [],
        content: "The quick brown fox jumps over the lazy dog.",
        tips: ["A classic pangram to test all reaches.", "Stay calm and keep the rhythm."],
        passingCriteria: { accuracy: 98, wpm: 40 },
        difficulty: 8,
        target_wpm: 50
    },

    // --- Tier 3: Advanced Reach (Lessons 26-40) ---
    {
        id: 26,
        title: "Numbers I: 1-5",
        phase: 3,
        description: "Left hand top row reaches.",
        keys: ['1', '2', '3', '4', '5'],
        content: "123 454 321 441 552 135 241",
        tips: ["Keep your palm still.", "Reach up from the home row."],
        passingCriteria: { accuracy: 95, wpm: 25 },
        difficulty: 8,
        target_wpm: 35
    },
    {
        id: 27,
        title: "Numbers II: 6-0",
        phase: 3,
        description: "Right hand top row reaches.",
        keys: ['6', '7', '8', '9', '0'],
        content: "678 909 876 006 779 680 796",
        tips: ["Don't look at the keys.", "Trust your ring and pinky fingers."],
        passingCriteria: { accuracy: 95, wpm: 25 },
        difficulty: 8,
        target_wpm: 35
    },
    {
        id: 28,
        title: "The Shift Key: Caps I",
        phase: 3,
        description: "Mastering the left and right shift.",
        keys: ['Shift'],
        content: "Aa Bb Cc Dd Ee Ff Gg Hh Ii Jj",
        tips: ["Use opposite-hand shift.", "Hold shift, tap key, release shift."],
        passingCriteria: { accuracy: 98, wpm: 30 },
        difficulty: 7,
        target_wpm: 40
    },
    {
        id: 29,
        title: "Reach: Z & X",
        phase: 3,
        description: "The bottom row outer reaches.",
        keys: ['z', 'x'],
        content: "az sx za xs zip axis zone extra",
        tips: ["Curl your pinky for Z.", "Ring finger for X."],
        passingCriteria: { accuracy: 97, wpm: 35 },
        difficulty: 8,
        target_wpm: 45
    },
    {
        id: 30,
        title: "Reach: Q & P",
        phase: 3,
        description: "Top row outer reaches.",
        keys: ['q', 'p'],
        content: "aq ;p qa p; quiet point quick piece",
        tips: ["Pinky reaches for both Q and P.", "Keep home row anchors."],
        passingCriteria: { accuracy: 97, wpm: 35 },
        difficulty: 8,
        target_wpm: 45
    },
    {
        id: 31,
        title: "Inner Reach: B & G",
        phase: 3,
        description: "Index finger lateral stretches.",
        keys: ['b', 'g'],
        content: "fb jg bf gj big bag get beg going",
        tips: ["Reach horizontally with your index.", "Snap back to the home row immediately."],
        passingCriteria: { accuracy: 98, wpm: 40 },
        difficulty: 6,
        target_wpm: 50
    },
    {
        id: 32,
        title: "Punctuation: ; & '",
        phase: 3,
        description: "Pinky reaches for separators.",
        keys: [';', "'"],
        content: "it's that's he's ; ; ; ; ; ;",
        tips: ["The pinky handles the edge keys.", "Stay light and nimble."],
        passingCriteria: { accuracy: 98, wpm: 40 },
        difficulty: 7,
        target_wpm: 50
    },
    {
        id: 33,
        title: "Punctuation: ! & ?",
        phase: 3,
        description: "Shifted punctuation marks.",
        keys: ['!', '?'],
        content: "Stop! Why? Help! Where? Go! When?",
        tips: ["! is Shift+1. ? is Shift+/.", "Breathe through the complex combos."],
        passingCriteria: { accuracy: 98, wpm: 35 },
        difficulty: 8,
        target_wpm: 45
    },
    {
        id: 34,
        title: "Advanced Rhythm I",
        phase: 3,
        description: "Focus on variable-length words.",
        keys: [],
        content: "the quick brown fox jumps over the lazy dog",
        tips: ["Focus on 'brown' and 'lazy'.", "Steady beat like a drum."],
        passingCriteria: { accuracy: 99, wpm: 45 },
        difficulty: 7,
        target_wpm: 60
    },
    {
        id: 35,
        title: "Number Row Sprint",
        phase: 3,
        description: "Mixing numbers into text.",
        keys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
        content: "In 1995, there were 10 people at 5 meetings.",
        tips: ["Don't let numbers slow you down.", "Move your whole hand slightly if needed."],
        passingCriteria: { accuracy: 97, wpm: 40 },
        difficulty: 9,
        target_wpm: 50
    },
    {
        id: 36,
        title: "Common Trigraghs",
        phase: 3,
        description: "Training THE, AND, ING.",
        keys: [],
        content: "the and ing the and ing showing things andings",
        tips: ["Treat these as single units of motion.", "Build speed through chunking."],
        passingCriteria: { accuracy: 99, wpm: 60 },
        difficulty: 6,
        target_wpm: 75
    },
    {
        id: 37,
        title: "The Suffix Suite",
        phase: 3,
        description: "Mastering -ION, -MENT, -NESS.",
        keys: [],
        content: "nation mention element comment happiness goodness",
        tips: ["Suffixes are the secret to 100+ WPM.", "Rhythmic flow is key."],
        passingCriteria: { accuracy: 98, wpm: 65 },
        difficulty: 8,
        target_wpm: 80
    },
    {
        id: 38,
        title: "Burst Drill: Home Row",
        type: 'burst',
        phase: 3,
        description: "Max speed on the home row only.",
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        content: "asdf jkl; a s d f j k l ; asdf jkl;",
        tips: ["raw twitch speed.", "Go as fast as possible."],
        passingCriteria: { accuracy: 90, wpm: 100 },
        difficulty: 5,
        target_wpm: 120
    },
    {
        id: 39,
        title: "Capitalization: Titles",
        phase: 3,
        description: "Proper nouns and headings.",
        keys: [],
        content: "London Paris New York Tokyo San Francisco",
        tips: ["Fast shift activation.", "Anticipate the capital letter."],
        passingCriteria: { accuracy: 98, wpm: 50 },
        difficulty: 7,
        target_wpm: 65
    },
    {
        id: 40,
        title: "Tier 3 Graduation",
        phase: 3,
        description: "Benchmark your Advanced Reach.",
        keys: [],
        content: "Complex text, including 10% numbers and symbols!",
        tips: ["This is a milestone test.", "Stay calm, stay precise."],
        passingCriteria: { accuracy: 99, wpm: 60 },
        difficulty: 9,
        target_wpm: 75
    },

    // --- Tier 4: Elite Code & Symbols (Lessons 41-60) ---
    {
        id: 41,
        title: "Brackets & Parens",
        phase: 4,
        description: "The logic of code: (), [], {}.",
        keys: ['(', ')', '[', ']', '{', '}'],
        content: "(params) [index] {block} ( ) [ ] { }",
        tips: ["Right pinky handles most of these.", "Anticipate the pair."],
        passingCriteria: { accuracy: 96, wpm: 30 },
        difficulty: 8,
        target_wpm: 45
    },
    {
        id: 42,
        title: "Operators: +, -, *, /",
        phase: 4,
        description: "Mathematical symbols.",
        keys: ['+', '-', '*', '/'],
        content: "a + b - c * d / e = f",
        tips: ["Requires shift for + and *.", "Keep fingers curled."],
        passingCriteria: { accuracy: 97, wpm: 35 },
        difficulty: 8,
        target_wpm: 50
    },
    {
        id: 43,
        title: "Logic Symbols: <, >, =, &",
        phase: 4,
        description: "Comparison and assignment.",
        keys: ['<', '>', '=', '&'],
        content: "x < y; a > b; x = y & z",
        tips: ["Precision over speed here.", "Watch the shift reaches."],
        passingCriteria: { accuracy: 97, wpm: 35 },
        difficulty: 8,
        target_wpm: 50
    },
    {
        id: 44,
        title: "Special: @, #, $, %",
        phase: 4,
        description: "Common special characters.",
        keys: ['@', '#', '$', '%'],
        content: "@user #tag $100 50%",
        tips: ["Look at the key if you must, but try not to.", "Build vertical muscle memory."],
        passingCriteria: { accuracy: 96, wpm: 35 },
        difficulty: 9,
        target_wpm: 45
    },
    {
        id: 45,
        title: "Code Snippet: Hello World",
        phase: 4,
        description: "Your first full line of code.",
        keys: [],
        content: "console.log(\"Hello, World!\");",
        tips: ["Quotes require shift.", "Semicolon at the end is vital."],
        passingCriteria: { accuracy: 98, wpm: 40 },
        difficulty: 7,
        target_wpm: 55
    },
    {
        id: 46,
        title: "CamelCase vs snake_case",
        phase: 4,
        description: "Naming conventions in programming.",
        keys: ['_'],
        content: "userProfile user_profile getData get_data",
        tips: ["Underscore is Shift+Minus.", "Maintain rhythm through the shift."],
        passingCriteria: { accuracy: 98, wpm: 50 },
        difficulty: 7,
        target_wpm: 65
    },
    {
        id: 47,
        title: "The Quote Maze",
        phase: 4,
        description: "Single and double quotes mixed.",
        keys: ["'", "\""],
        content: "It said, 'Don't do it.' She said, \"Wait!\"",
        tips: ["Double quotes are Shift+SingleQuote.", "Focus on the pinky pivot."],
        passingCriteria: { accuracy: 98, wpm: 45 },
        difficulty: 8,
        target_wpm: 60
    },
    {
        id: 48,
        title: "Logic Gates: && and ||",
        phase: 4,
        description: "Boolean logic symbols.",
        keys: ['&', '|'],
        content: "true && false; a || b; logic gates",
        tips: ["Vertical bars are Shift+Backslash.", "Ampersand is Shift+7."],
        passingCriteria: { accuracy: 97, wpm: 40 },
        difficulty: 9,
        target_wpm: 55
    },
    {
        id: 49,
        title: "CSS Selectors",
        phase: 4,
        description: "Classes, IDs, and nesting.",
        keys: ['.', '#'],
        content: ".header .nav #logo .item:hover",
        tips: ["Colon is Shift+Semicolon.", "Stay fast on the dots."],
        passingCriteria: { accuracy: 98, wpm: 55 },
        difficulty: 7,
        target_wpm: 70
    },
    {
        id: 50,
        title: "Mid-Tier Elite Test",
        phase: 4,
        description: "Benchmark your symbol speed.",
        keys: [],
        content: "if (x > 10 && y <= 5) { return true; }",
        tips: ["This combines logic, punctuation, and shift.", "Precision is paramount."],
        passingCriteria: { accuracy: 98, wpm: 50 },
        difficulty: 9,
        target_wpm: 65
    },
    {
        id: 51,
        title: "Burst: Number Bank",
        type: 'burst',
        phase: 4,
        description: "Raw speed on the number row.",
        keys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
        content: "12345 67890 24680 13579",
        tips: ["Try to hover your hands slightly higher.", "Focus on the tactile feel of the reach."],
        passingCriteria: { accuracy: 90, wpm: 80 },
        difficulty: 9,
        target_wpm: 100
    },
    {
        id: 52,
        title: "Indentation & Tabs",
        phase: 4,
        description: "Mastering the Tab reach.",
        keys: ['Tab'],
        content: "  line1\n    line2\n  line3",
        tips: ["Tab is left pinky.", "Keep your hand position stable."],
        passingCriteria: { accuracy: 98, wpm: 40 },
        difficulty: 8,
        target_wpm: 55
    },
    {
        id: 53,
        title: "Function Definitions",
        phase: 4,
        description: "Full coding structure.",
        keys: [],
        content: "function getSum(a, b) { return a + b; }",
        tips: ["Rhythm through the keywords and symbols.", "Don't pause at the brackets."],
        passingCriteria: { accuracy: 98, wpm: 55 },
        difficulty: 8,
        target_wpm: 70
    },
    {
        id: 54,
        title: "Arrow Functions",
        phase: 4,
        description: "Modern JavaScript syntax.",
        keys: ['=', '>'],
        content: "const add = (a, b) => a + b;",
        tips: ["The => combo should be a single flick.", "Focus on the transition."],
        passingCriteria: { accuracy: 98, wpm: 60 },
        difficulty: 8,
        target_wpm: 75
    },
    {
        id: 55,
        title: "Template Literals",
        phase: 4,
        description: "Backticks and interpolation.",
        keys: ['`', '$'],
        content: "`${user.name} is ${age} years old`",
        tips: ["Backtick is above Tab.", "Shift+4 for the dollar sign."],
        passingCriteria: { accuracy: 97, wpm: 50 },
        difficulty: 9,
        target_wpm: 65
    },
    {
        id: 56,
        title: "Object Literals",
        phase: 4,
        description: "Key-value pair syntax.",
        keys: [':', ','],
        content: "{ key: \"value\", id: 101, active: true }",
        tips: ["Colon requires shift.", "Comma separates the flow."],
        passingCriteria: { accuracy: 98, wpm: 55 },
        difficulty: 8,
        target_wpm: 70
    },
    {
        id: 57,
        title: "Arrays & Mapping",
        phase: 4,
        description: "List processing syntax.",
        keys: ['[', ']', '.', '('],
        content: "items.map(item => item.id);",
        tips: ["Method chaining requires precise dots.", "Map is a common coding trigraph."],
        passingCriteria: { accuracy: 99, wpm: 60 },
        difficulty: 7,
        target_wpm: 80
    },
    {
        id: 58,
        title: "Master Mode: Syntax I",
        isMasterMode: true,
        phase: 4,
        description: "Perfect code. Zero errors allowed.",
        keys: [],
        content: "export default function App() { return <div />; }",
        tips: ["One mistype resets everything.", "Go slow and be 100% sure."],
        passingCriteria: { accuracy: 100, wpm: 50 },
        difficulty: 10,
        target_wpm: 60
    },
    {
        id: 59,
        title: "Difficult Combos: Symbols",
        phase: 4,
        description: "The 'Outer-Reach' nightmare.",
        keys: ['~', '`', '|', '\\', '{', '}'],
        content: "~~temp~~ { \\ o / } | ~ | `test`",
        tips: ["These keys are rarely used but vital for speed.", "Strengthen your outer fingers."],
        passingCriteria: { accuracy: 96, wpm: 40 },
        difficulty: 10,
        target_wpm: 55
    },
    {
        id: 60,
        title: "Tier 4 Elite Graduation",
        phase: 4,
        description: "The ultimate coding benchmark.",
        keys: [],
        content: "async function fetchData() { const res = await fetch(url); }",
        tips: ["Combine everything: keywords, symbols, casing.", "You are now a pro-level typist."],
        passingCriteria: { accuracy: 98, wpm: 70 },
        difficulty: 10,
        target_wpm: 85
    },

    // --- Tier 5: Professional Specialized (Lessons 61-75) ---
    {
        id: 61,
        title: "Markdown Mastery",
        phase: 4,
        description: "Formatting symbols: #, *, -, [].",
        keys: ['#', '*', '-'],
        content: "# Heading\n- List Item\n**Bold Text** [Link](url)",
        tips: ["Markdown is the global standard for documentation.", "Fast reach for # and *."],
        passingCriteria: { accuracy: 98, wpm: 60 },
        difficulty: 7,
        target_wpm: 80
    },
    {
        id: 62,
        title: "HTML/JSX Structure",
        phase: 4,
        description: "Tags, attributes, and closing tags.",
        keys: ['<', '>', '/', '='],
        content: "<div className=\"container\">Text</div>",
        tips: ["Tags are the skeleton of the web.", "Precision with quotes and slashes."],
        passingCriteria: { accuracy: 98, wpm: 65 },
        difficulty: 8,
        target_wpm: 85
    },
    {
        id: 63,
        title: "JSON Data Stream",
        phase: 4,
        description: "The language of data.",
        keys: ['{', '}', ':', ',', '"'],
        content: "{\"id\": 1, \"name\": \"Pro\", \"level\": 75}",
        tips: ["Braces and quotes are the core of JSON.", "Keep your hands relaxed during the symbol heavy rain."],
        passingCriteria: { accuracy: 97, wpm: 55 },
        difficulty: 9,
        target_wpm: 70
    },
    {
        id: 64,
        title: "Regex: The Final Boss",
        phase: 4,
        description: "Pattern matching symbols: /, ^, $, +, ?.",
        keys: ['/', '^', '$', '+', '?'],
        content: "/^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$/",
        tips: ["Regex is the true test of symbol speed.", "Don't think about the meaning, just the shapes."],
        passingCriteria: { accuracy: 95, wpm: 40 },
        difficulty: 10,
        target_wpm: 55
    },
    {
        id: 65,
        title: "Burst: Alpha-Numeric",
        type: 'burst',
        phase: 4,
        description: "Mixing letters and numbers at max speed.",
        keys: [],
        content: "alpha1 beta2 gamma3 delta4 epsilon5 zeta6",
        tips: ["raw twitch coordination.", "Sync your hand movements with your eyes."],
        passingCriteria: { accuracy: 90, wpm: 90 },
        difficulty: 9,
        target_wpm: 110
    },
    {
        id: 66,
        title: "Global Hotkeys: Control bank",
        phase: 4,
        description: "Anticipating multi-key shortcuts.",
        keys: [],
        content: "ctrl+c ctrl+v cmd+opt+shift+L",
        tips: ["Focus on the modifier finger positions.", "Stay stable through the stretches."],
        passingCriteria: { accuracy: 98, wpm: 50 },
        difficulty: 9,
        target_wpm: 70
    },
    {
        id: 67,
        title: "Shell Commands",
        phase: 4,
        description: "CLI syntax: cd, ls, mkdir, --flag.",
        keys: ['-', '/'],
        content: "git commit -m \"feat: add quests\" --force",
        tips: ["Dashes are common in CLI.", "Quotes are essential for messages."],
        passingCriteria: { accuracy: 98, wpm: 70 },
        difficulty: 7,
        target_wpm: 90
    },
    {
        id: 68,
        title: "SQL Queries",
        phase: 4,
        description: "Data manipulation language.",
        keys: ['*', '(', ')', '='],
        content: "SELECT * FROM users WHERE level > 50;",
        tips: ["All-caps keywords require fast shift or caps-lock.", "Semicolon is the query terminator."],
        passingCriteria: { accuracy: 98, wpm: 75 },
        difficulty: 8,
        target_wpm: 95
    },
    {
        id: 69,
        title: "Scientific Notation",
        phase: 4,
        description: "Math in the digital age.",
        keys: ['e', '^'],
        content: "6.022e23; 3.14159; x^2 + y^2 = r^2",
        tips: ["Caret is Shift+6.", "Transition between letters and numbers."],
        passingCriteria: { accuracy: 97, wpm: 60 },
        difficulty: 9,
        target_wpm: 80
    },
    {
        id: 70,
        title: "The Deep Code Dive",
        phase: 4,
        description: "Full module structure.",
        keys: [],
        content: "import { useState } from 'react'; export default function App() {}",
        tips: ["Importing is the start of every file.", "Rhythm through the keywords."],
        passingCriteria: { accuracy: 99, wpm: 80 },
        difficulty: 8,
        target_wpm: 100
    },
    {
        id: 71,
        title: "Pacing Drill: 100 WPM",
        phase: 4,
        description: "Steady consistency at elite speeds.",
        keys: [],
        content: "Consistency is the key to unlocking the true potential of your speed.",
        tips: ["Maintain a perfectly steady rhythm.", "No pauses, no bursts."],
        passingCriteria: { accuracy: 99, wpm: 100 },
        difficulty: 8,
        target_wpm: 110
    },
    {
        id: 72,
        title: "Master Mode: Elite Code",
        isMasterMode: true,
        phase: 4,
        description: "Perfect professional code. No errors.",
        keys: [],
        content: "const response = await api.post('/v1/data', { payload });",
        tips: ["One mistake = Reset.", "The ultimate test of precision."],
        passingCriteria: { accuracy: 100, wpm: 80 },
        difficulty: 10,
        target_wpm: 95
    },
    {
        id: 73,
        title: "Burst: The Finale Sprint",
        type: 'burst',
        phase: 4,
        description: "Final 15-second speed explosion.",
        keys: [],
        content: "speed speed speed speed speed speed speed",
        tips: ["Give it everything you've got.", "Twitch speed to the max."],
        passingCriteria: { accuracy: 85, wpm: 150 },
        difficulty: 10,
        target_wpm: 180
    },
    {
        id: 74,
        title: "The 120 WPM Plateau Breaker",
        phase: 4,
        description: "Breaking the sound barrier of typing.",
        keys: [],
        content: "You are the master of the keys. You have conquered the digital board.",
        tips: ["Relax your hands. Speed flows from relaxation.", "Trust your training."],
        passingCriteria: { accuracy: 99, wpm: 120 },
        difficulty: 10,
        target_wpm: 130
    },
    {
        id: 75,
        title: "LEGEND FINALE (150+ WPM)",
        phase: 4,
        description: "The Hero's Journey ends here.",
        keys: [],
        content: "To type at the speed of thought is to become one with the machine. Your journey is complete. You are a Legend.",
        tips: ["The finale of the 75-lesson Master Curriculum.", "You are elite. You are the God of Flow."],
        passingCriteria: { accuracy: 99, wpm: 150 },
        difficulty: 10,
        target_wpm: 160
    }
];
