import { Lesson } from '../types';

export const HERO_CURRICULUM: Lesson[] = [
    // --- PHASE 1: FOUNDATION (Lessons 1-20) ---
    // Goal: Home Row, Posture, 0-20 WPM
    {
        id: 1,
        title: "Home Row Anchors",
        phase: 1,
        description: "Meet your home row anchors: F and J.",
        keys: ['f', 'j'],
        content: "f j f j ff jj fjf jfj f j f j ff jj",
        tips: ["Feel the bumps on F and J – your index fingers live here!", "Keep your fingers curved like you're holding a tennis ball."],
        passingCriteria: { accuracy: 100, wpm: 5 },
        difficulty: 1,
        target_wpm: 10
    },
    {
        id: 2,
        title: "Inner Home Row",
        phase: 1,
        description: "Adding D and K to your anchors.",
        keys: ['d', 'k'],
        content: "fd jk df kj fdd jkk dkf jdf f d k j",
        tips: ["D is for your left middle finger.", "K is for your right middle finger."],
        passingCriteria: { accuracy: 100, wpm: 8 },
        difficulty: 1,
        target_wpm: 12
    },
    {
        id: 3,
        title: "The Ring Reach",
        phase: 1,
        description: "Introducing S and L.",
        keys: ['s', 'l'],
        content: "fs dj kl sl sk dl sss lll sls dld s l s l",
        tips: ["Use your ring fingers for S and L.", "Don't look at the keyboard – trust the bumps!"],
        passingCriteria: { accuracy: 98, wpm: 10 },
        difficulty: 2,
        target_wpm: 15
    },
    {
        id: 4,
        title: "Pinky Power",
        phase: 1,
        description: "The home row is complete with A and ;.",
        keys: ['a', ';'],
        content: "asdf jkl; a; a; ds; fl a;s l;d fjk a ; a ;",
        tips: ["Your pinkies are small but mighty!", "Rest your palms lightly or keep them slightly elevated."],
        passingCriteria: { accuracy: 98, wpm: 12 },
        difficulty: 2,
        target_wpm: 18
    },
    {
        id: 5,
        title: "Rhythm & Flow",
        phase: 1,
        description: "Combining everything on the home row.",
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        content: "asdf jkl; fdsa ;lkj dads lads asks fall a s d f j k l ;",
        tips: ["Focus on rhythm, not speed.", "Accuracy first, speed will follow naturally."],
        passingCriteria: { accuracy: 98, wpm: 15 },
        difficulty: 2,
        target_wpm: 20
    },
    {
        id: 6,
        title: "Word Rhythm I",
        phase: 1,
        description: "Short common words found only on the home row.",
        keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        content: "sad dad lad add flask salad alfalfa dads lads",
        tips: ["Try to maintain a steady beat.", "Your fingers should always return to the anchor points."],
        passingCriteria: { accuracy: 99, wpm: 18 },
        difficulty: 3,
        target_wpm: 22
    },
    {
        id: 7,
        title: "The Thumb Jump",
        phase: 1,
        description: "Mastering the Spacebar with your thumbs.",
        keys: [' '],
        content: "f f f j j j d d d k k k s s s l l l a a a ; ; ;",
        tips: ["Use either thumb for the spacebar.", "Don't pause too long between words."],
        passingCriteria: { accuracy: 100, wpm: 20 },
        difficulty: 3,
        target_wpm: 25
    },
    {
        id: 8,
        title: "Middle Reach: E & I",
        phase: 1,
        description: "Reaching up to the top row.",
        keys: ['e', 'i'],
        content: "de ki ed ik died eke side lake kid slide desk mask",
        tips: ["Left middle for E, Right middle for I.", "Keep the movement minimal."],
        passingCriteria: { accuracy: 98, wpm: 15 },
        difficulty: 3,
        target_wpm: 20
    },
    {
        id: 9,
        title: "Index Reach: R & U",
        phase: 1,
        description: "Index fingers reaching for R and U.",
        keys: ['r', 'u'],
        content: "fr ju rf uj fur rude red user sure rust dusk rude",
        tips: ["Reach up from F and J.", "Quick snap back to the home row."],
        passingCriteria: { accuracy: 98, wpm: 18 },
        difficulty: 3,
        target_wpm: 22
    },
    {
        id: 10,
        title: "Index Reach: T & Y",
        phase: 1,
        description: "Internal index stretches for T and Y.",
        keys: ['t', 'y'],
        content: "ft jy tf yj try toy that they stayed year",
        tips: ["Diagonal stretch from the home row.", "Minimize hand movement."],
        passingCriteria: { accuracy: 98, wpm: 20 },
        difficulty: 3,
        target_wpm: 25
    },
    {
        id: 11,
        title: "Top Row Vowels: I & O",
        phase: 1,
        description: "Mastering the core vowels of the top row.",
        keys: ['i', 'o'],
        content: "ki lo ik ol oil look lion look cook food door",
        tips: ["Focus on the right hand reach.", "Keep your fingers curved."],
        passingCriteria: { accuracy: 98, wpm: 22 },
        difficulty: 3,
        target_wpm: 28
    },
    {
        id: 12,
        title: "Home Row Variation",
        phase: 1,
        description: "Advanced home row patterns.",
        keys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l'],
        content: "ah had has sag dad fall flask salad glass shall",
        tips: ["G and H are common index reached.", "Stay centered on F and J."],
        passingCriteria: { accuracy: 99, wpm: 25 },
        difficulty: 3,
        target_wpm: 30
    },
    {
        id: 13,
        title: "Bottom Row: C & M",
        phase: 1,
        description: "Diving down to C and M.",
        keys: ['c', 'm'],
        content: "dc km cd mk come mica mice make music camp come",
        tips: ["C is left middle, M is right middle.", "Reach directly down."],
        passingCriteria: { accuracy: 98, wpm: 20 },
        difficulty: 4,
        target_wpm: 28
    },
    {
        id: 14,
        title: "Bottom Row: V & N",
        phase: 1,
        description: "Index reaches for V and N.",
        keys: ['v', 'n'],
        content: "fv jn vf nj van vine never view vein navy main",
        tips: ["V and N are directly below your anchors.", "Fast, light taps."],
        passingCriteria: { accuracy: 98, wpm: 22 },
        difficulty: 4,
        target_wpm: 30
    },
    {
        id: 15,
        title: "Bottom Row: B & G",
        phase: 1,
        description: "Index stretches to B and G.",
        keys: ['b', 'g'],
        content: "fb jg bf gj big bag get beg going bag big get",
        tips: ["B is a slight stretch for the left index.", "G is a horizontal index move."],
        passingCriteria: { accuracy: 98, wpm: 22 },
        difficulty: 4,
        target_wpm: 30
    },
    {
        id: 16,
        title: "The Shift Keys",
        phase: 1,
        description: "Mastering capital letters.",
        keys: ['Shift'],
        content: "The Red Dog Runs Fast. John Likes Cake. Apple Pie.",
        tips: ["Use the opposite hand for Shift.", "Hold Shift, tap key, release."],
        passingCriteria: { accuracy: 97, wpm: 20 },
        difficulty: 4,
        target_wpm: 28
    },
    {
        id: 17,
        title: "Punctuation Basics",
        phase: 1,
        description: "Comma and Period integration.",
        keys: [',', '.'],
        content: "I. We, They. Run, fast. Stop. Wait, listen. Go.",
        tips: ["Comma is under K, Period is under L.", "Follow with one space."],
        passingCriteria: { accuracy: 98, wpm: 20 },
        difficulty: 4,
        target_wpm: 30
    },
    {
        id: 18,
        title: "Common Phrases I",
        phase: 1,
        description: "Small words that build speed.",
        keys: [],
        content: "the of and to a in is that it he was for on are",
        tips: ["Don't overthink these words.", "Let your fingers flow naturally."],
        passingCriteria: { accuracy: 99, wpm: 25 },
        difficulty: 4,
        target_wpm: 35
    },
    {
        id: 19,
        title: "Foundation Review",
        phase: 1,
        description: "Reviewing all foundational reaches.",
        keys: [],
        content: "The quick red fox jumps. Home row is where we live.",
        tips: ["Keep your accuracy high.", "Smooth rhythm over raw speed."],
        passingCriteria: { accuracy: 99, wpm: 28 },
        difficulty: 5,
        target_wpm: 38
    },
    {
        id: 20,
        title: "Foundation Graduation",
        phase: 1,
        description: "End of Week 2 benchmark.",
        keys: [],
        content: "Mastering the home row and basic reaches is the key to elite speed.",
        tips: ["Stay calm, stay precise.", "Maintain 99%+ accuracy for milestone."],
        passingCriteria: { accuracy: 99, wpm: 30 },
        difficulty: 5,
        target_wpm: 40
    },

    // --- PHASE 2: EXPANSION (Lessons 21-40) ---
    // Goal: Top/Bottom Row mastery, 20-40 WPM
    {
        id: 21,
        title: "Top Row: Q & P",
        phase: 2,
        description: "Outer pinky reaches for Q and P.",
        keys: ['q', 'p'],
        content: "aq ;p qa p; quiet point quick piece queen pile",
        tips: ["Pinkies stay light.", "Don't shift your whole hand."],
        passingCriteria: { accuracy: 97, wpm: 25 },
        difficulty: 5,
        target_wpm: 35
    },
    {
        id: 22,
        title: "Top Row: W & Z",
        phase: 2,
        description: "Left hand outer reaches.",
        keys: ['w', 'z'],
        content: "sw az ws za was zone win zip will zoom wall",
        tips: ["W is ring finger, Z is pinky.", "Quick vertical jumps."],
        passingCriteria: { accuracy: 97, wpm: 25 },
        difficulty: 5,
        target_wpm: 35
    },
    {
        id: 23,
        title: "Top Row: X & Y",
        phase: 2,
        description: "Mixing outer and inner stretches.",
        keys: ['x', 'y'],
        content: "sx jy xs yj exit year xray yellow axis youth",
        tips: ["X is left ring, Y is right index.", "Maintain your center."],
        passingCriteria: { accuracy: 97, wpm: 25 },
        difficulty: 6,
        target_wpm: 35
    },
    {
        id: 24,
        title: "Digraph mastery: TH",
        phase: 2,
        description: "The most common letter pair.",
        keys: ['t', 'h'],
        content: "the that they then there truth with math bath cloth",
        tips: ["Think of TH as a single 'chord'.", "Let it flow as one motion."],
        passingCriteria: { accuracy: 99, wpm: 35 },
        difficulty: 5,
        target_wpm: 45
    },
    {
        id: 25,
        title: "Digraph mastery: ER",
        phase: 2,
        description: "Common suffix and internal pair.",
        keys: ['e', 'r'],
        content: "her there where water paper power river silver",
        tips: ["Middle finger to index finger movement.", "Stay light on the keys."],
        passingCriteria: { accuracy: 99, wpm: 35 },
        difficulty: 5,
        target_wpm: 45
    },
    {
        id: 26,
        title: "Common Digraphs: IN, AN, RE",
        phase: 2,
        description: "High-speed combinations.",
        keys: ['i', 'n', 'a', 'r', 'e'],
        content: "in an re into inside and rare real rain area",
        tips: ["Build muscle memory for these 'chunks'.", "Don't pause between the letters."],
        passingCriteria: { accuracy: 99, wpm: 40 },
        difficulty: 6,
        target_wpm: 50
    },
    {
        id: 27,
        title: "Double Letters: EE, OO, LL",
        phase: 2,
        description: "Rhythm building with double taps.",
        keys: ['e', 'o', 'l'],
        content: "see tree free keep moon soon food door fall hill",
        tips: ["Double taps require a bouncy finger.", "Maintain the beat."],
        passingCriteria: { accuracy: 100, wpm: 35 },
        difficulty: 5,
        target_wpm: 45
    },
    {
        id: 28,
        title: "The 'TION' Suite",
        phase: 2,
        description: "Mastering the common ending.",
        keys: ['t', 'i', 'o', 'n'],
        content: "nation ocean action option section station motion",
        tips: ["Right hand does the heavy lifting.", "Flow through the sequence."],
        passingCriteria: { accuracy: 98, wpm: 40 },
        difficulty: 6,
        target_wpm: 50
    },
    {
        id: 29,
        title: "The 'ING' Suite",
        phase: 2,
        description: "Continuous action suffix.",
        keys: ['i', 'n', 'g'],
        content: "running jumping flying singing doing being going",
        tips: ["Fast right index flow.", "Build speed on the suffix."],
        passingCriteria: { accuracy: 98, wpm: 40 },
        difficulty: 6,
        target_wpm: 50
    },
    {
        id: 30,
        title: "Expansion Review I",
        phase: 2,
        description: "Reviewing all top/bottom row reaches.",
        keys: [],
        content: "The queen was quiet at the station near the river.",
        tips: ["Combine everything you've learned this week.", "Keep a steady rhythm."],
        passingCriteria: { accuracy: 99, wpm: 40 },
        difficulty: 7,
        target_wpm: 55
    },
    {
        id: 31,
        title: "Numbers Intro: 1, 2, 3",
        phase: 2,
        description: "Left hand top-row numbers.",
        keys: ['1', '2', '3'],
        content: "1 2 3 123 321 11 22 33 13 21 23",
        tips: ["Reach up from your ring and middle fingers.", "Stay relaxed."],
        passingCriteria: { accuracy: 96, wpm: 20 },
        difficulty: 7,
        target_wpm: 30
    },
    {
        id: 32,
        title: "Numbers Intro: 4, 5, 6",
        phase: 2,
        description: "Middle-reach numbers.",
        keys: ['4', '5', '6'],
        content: "4 5 6 456 654 44 55 66 46 54 56",
        tips: ["Index fingers reach for these.", "Quick snap back."],
        passingCriteria: { accuracy: 96, wpm: 20 },
        difficulty: 7,
        target_wpm: 30
    },
    {
        id: 33,
        title: "Numbers Intro: 7, 8, 9, 0",
        phase: 2,
        description: "Right hand top-row numbers.",
        keys: ['7', '8', '9', '0'],
        content: "7 8 9 0 789 098 77 88 99 00 70 89",
        tips: ["Right index to pinky reach.", "Don't look at the keys."],
        passingCriteria: { accuracy: 96, wpm: 20 },
        difficulty: 7,
        target_wpm: 30
    },
    {
        id: 34,
        title: "Full Number Row",
        phase: 2,
        description: "Coordinating all digits.",
        keys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
        content: "1234567890 0987654321 2468 1357 05",
        tips: ["Maintain home row position.", "Minimize whole-hand movement."],
        passingCriteria: { accuracy: 95, wpm: 25 },
        difficulty: 8,
        target_wpm: 35
    },
    {
        id: 35,
        title: "Sentence Construction I",
        phase: 2,
        description: "Building longer sentences.",
        keys: [],
        content: "There are 7 days in a week and 12 months in a year.",
        tips: ["Mixing numbers and words naturally.", "Focus on the context."],
        passingCriteria: { accuracy: 98, wpm: 35 },
        difficulty: 7,
        target_wpm: 45
    },
    {
        id: 36,
        title: "Advanced Reach: B & V",
        phase: 2,
        description: "Left hand bottom row agility.",
        keys: ['b', 'v'],
        content: "be very believe view brave vivid blue vibe",
        tips: ["Index finger focus.", "Quick movements down and back."],
        passingCriteria: { accuracy: 98, wpm: 40 },
        difficulty: 7,
        target_wpm: 50
    },
    {
        id: 37,
        title: "Advanced Reach: M & N",
        phase: 2,
        description: "Right hand bottom row agility.",
        keys: ['m', 'n'],
        content: "moon noon main name men man music money",
        tips: ["Middle and index finger movement.", "Stay precise."],
        passingCriteria: { accuracy: 98, wpm: 40 },
        difficulty: 7,
        target_wpm: 50
    },
    {
        id: 38,
        title: "Speed Sprint: Top Row",
        type: 'burst',
        phase: 2,
        description: "Max speed on the top row.",
        keys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
        content: "qwerty uiop we try top you our red power",
        tips: ["Go fast, but stay accurate.", "15-second explosion."],
        passingCriteria: { accuracy: 90, wpm: 50 },
        difficulty: 8,
        target_wpm: 70
    },
    {
        id: 39,
        title: "Expansion Review II",
        phase: 2,
        description: "Consolidating all expansion reaches.",
        keys: [],
        content: "Quickly move between the top and bottom rows now.",
        tips: ["Smooth transitions are the secret.", "Stay light."],
        passingCriteria: { accuracy: 99, wpm: 40 },
        difficulty: 8,
        target_wpm: 55
    },
    {
        id: 40,
        title: "Expansion Graduation",
        phase: 2,
        description: "End of Week 4 benchmark.",
        keys: [],
        content: "You have conquered the alphabet and numbers. Proficiency is next.",
        tips: ["Accuracy above 99.5% is the goal.", "Maintain your center."],
        passingCriteria: { accuracy: 99.5, wpm: 45 },
        difficulty: 8,
        target_wpm: 60
    },

    // --- PHASE 3: MOMENTUM (Lessons 41-60) ---
    // Goal: Symbols, Rhythms, 40-75 WPM
    {
        id: 41,
        title: "Shifted Symbols: ! @ #",
        phase: 3,
        description: "Upper row symbols.",
        keys: ['!', '@', '#'],
        content: "Stop! @user #tag !! @@ ## !#!# @!@!",
        tips: ["Hold Shift with your right pinky for these.", "Precise reaches."],
        passingCriteria: { accuracy: 95, wpm: 30 },
        difficulty: 8,
        target_wpm: 45
    },
    {
        id: 42,
        title: "Shifted Symbols: $ % ^",
        phase: 3,
        description: "Middle-row secondary symbols.",
        keys: ['$', '%', '^'],
        content: "$100 50% Up^ 2^2 $ $ % % ^ ^ $%$",
        tips: ["Index and middle reach.", "Stay calm with the Shift move."],
        passingCriteria: { accuracy: 95, wpm: 30 },
        difficulty: 8,
        target_wpm: 45
    },
    {
        id: 43,
        title: "Shifted Symbols: & * ( )",
        phase: 3,
        description: "Right hand shifted symbols.",
        keys: ['&', '*', '(', ')'],
        content: "Law & Order *bolded* (parentheses) &*& (())",
        tips: ["Right hand pinky/ring reach.", "Hold Shift with your left pinky."],
        passingCriteria: { accuracy: 95, wpm: 30 },
        difficulty: 8,
        target_wpm: 45
    },
    {
        id: 44,
        title: "Punctuation II: : ; ' \"",
        phase: 3,
        description: "Outer right hand reaches.",
        keys: [':', ';', "'", "\""],
        content: "Wait: \"hello\" it's John's; yes: wait.",
        tips: ["Quotes and colons require fast shift.", "Stay light on the pinky."],
        passingCriteria: { accuracy: 96, wpm: 35 },
        difficulty: 8,
        target_wpm: 50
    },
    {
        id: 45,
        title: "Expression: ? / \\ |",
        phase: 3,
        description: "Diving deeper into logic symbols.",
        keys: ['?', '/', '\\', '|'],
        content: "Why? /path/ \\test\\ | bar | ?",
        tips: ["Question mark is Shift+Slash.", "Pipe is Shift+Backslash."],
        passingCriteria: { accuracy: 95, wpm: 35 },
        difficulty: 9,
        target_wpm: 50
    },
    {
        id: 46,
        title: "Brackets: [] {}",
        phase: 3,
        description: "Mastering key grouping symbols.",
        keys: ['[', ']', '{', '}'],
        content: "[list] {object} [ ] { } { [ ] }",
        tips: ["Right pinky reach.", "Horizontal alignment focus."],
        passingCriteria: { accuracy: 96, wpm: 35 },
        difficulty: 9,
        target_wpm: 50
    },
    {
        id: 47,
        title: "Mathematical Flow: +, -, =, *",
        phase: 3,
        description: "Rhythm through math.",
        keys: ['+', '-', '=', '*'],
        content: "1 + 2 - 3 = 0; 5 * 10 = 50",
        tips: ["Mixing numbers and symbols.", "Stay predictable."],
        passingCriteria: { accuracy: 97, wpm: 40 },
        difficulty: 9,
        target_wpm: 55
    },
    {
        id: 48,
        title: "CamelCase training",
        phase: 3,
        description: "Programming naming styles.",
        keys: [],
        content: "userProfile dataStream getInfo setTarget",
        tips: ["Fast shift activation for capitals.", "Let your fingers flow."],
        passingCriteria: { accuracy: 98, wpm: 50 },
        difficulty: 7,
        target_wpm: 70
    },
    {
        id: 49,
        title: "snake_case training",
        phase: 3,
        description: "Underscore integration.",
        keys: ['_'],
        content: "user_profile data_stream get_info set_target",
        tips: ["Underscore is Shift+Minus.", "Maintain your rhythm."],
        passingCriteria: { accuracy: 98, wpm: 50 },
        difficulty: 7,
        target_wpm: 70
    },
    {
        id: 50,
        title: "Momentum Review I",
        phase: 3,
        description: "Reviewing symbols and casings.",
        keys: [],
        content: "The {user_id} is @active! (Value: 100%)",
        tips: ["High complexity text.", "Slow down if accuracy drops below 98%."],
        passingCriteria: { accuracy: 98, wpm: 50 },
        difficulty: 9,
        target_wpm: 70
    },
    {
        id: 51,
        title: "Elite Trigraph: THE",
        phase: 3,
        description: "Speed drill for THE.",
        keys: [],
        content: "the the the the the the the the the the",
        tips: ["Treat it as a single musical trill.", "Go as fast as possible."],
        passingCriteria: { accuracy: 100, wpm: 70 },
        difficulty: 6,
        target_wpm: 100
    },
    {
        id: 52,
        title: "Elite Trigraph: AND",
        phase: 3,
        description: "Speed drill for AND.",
        keys: [],
        content: "and and and and and and and and and and",
        tips: ["Coordinate between both hands.", "Steady beat."],
        passingCriteria: { accuracy: 100, wpm: 70 },
        difficulty: 6,
        target_wpm: 100
    },
    {
        id: 53,
        title: "Elite Suffix: ING",
        phase: 3,
        description: "Speed drill for ING.",
        keys: [],
        content: "ing ing ing ing ing ing ing ing ing ing",
        tips: ["Right hand agility focus.", "Clear, snappy taps."],
        passingCriteria: { accuracy: 100, wpm: 70 },
        difficulty: 6,
        target_wpm: 100
    },
    {
        id: 54,
        title: "Word Chunking I",
        phase: 3,
        description: "Combining trigraphs.",
        keys: [],
        content: "the and ing bringing things standing thanding",
        tips: ["Combine your 'trill' training.", "Zero pauses between chunks."],
        passingCriteria: { accuracy: 99, wpm: 60 },
        difficulty: 7,
        target_wpm: 80
    },
    {
        id: 55,
        title: "Metronome: 60 BPM",
        phase: 3,
        description: "Rhythm sync at steady speed.",
        keys: [],
        content: "Type one letter per beat of the metronome now.",
        tips: ["Follow the pulse exactly.", "Consistency over raw speed."],
        passingCriteria: { accuracy: 100, wpm: 60 },
        difficulty: 8,
        target_wpm: 60
    },
    {
        id: 56,
        title: "Accuracy Master I",
        isMasterMode: true,
        phase: 3,
        description: "Perfect practice drill.",
        keys: [],
        content: "To err is human, but to type perfectly is elite.",
        tips: ["Restart on ANY error.", "Slow and steady wins this drill."],
        passingCriteria: { accuracy: 100, wpm: 40 },
        difficulty: 10,
        target_wpm: 50
    },
    {
        id: 57,
        title: "Speed Burst: Short Vowels",
        type: 'burst',
        phase: 3,
        description: "High speed vowel strings.",
        keys: ['a', 'e', 'i', 'o', 'u'],
        content: "aeiou uoiea aeae iouio ouaei eaeiou",
        tips: ["Finger agility drill.", "Quick, independent movement."],
        passingCriteria: { accuracy: 90, wpm: 80 },
        difficulty: 9,
        target_wpm: 100
    },
    {
        id: 58,
        title: "Pacing Drill: 60 WPM",
        phase: 3,
        description: "Maintain a steady 60 WPM flow.",
        keys: [],
        content: "Consistency at this speed will build a huge foundation.",
        tips: ["Don't speed up or slow down.", "Flow like water."],
        passingCriteria: { accuracy: 99, wpm: 60 },
        difficulty: 8,
        target_wpm: 65
    },
    {
        id: 59,
        title: "Momentum Review II",
        phase: 3,
        description: "Consolidating all Week 6 skills.",
        keys: [],
        content: "Rhythm, symbols, and suffixes are the secrets to flow.",
        tips: ["Stay present in the lesson.", "Focus on the next word."],
        passingCriteria: { accuracy: 99.5, wpm: 65 },
        difficulty: 9,
        target_wpm: 75
    },
    {
        id: 60,
        title: "Momentum Graduation",
        phase: 3,
        description: "End of Week 6 benchmark.",
        keys: [],
        content: "You are now proficient with the entire standard keyboard layout.",
        tips: ["Benchmark your speed.", "Accuracy must be 99.5%+."],
        passingCriteria: { accuracy: 99.5, wpm: 70 },
        difficulty: 9,
        target_wpm: 80
    },

    // --- PHASE 4: PROFICIENCY (Lessons 61-80) ---
    // Goal: Flow, Words, 75-110 WPM
    {
        id: 61,
        title: "Long Words I: Foundation",
        phase: 4,
        description: "Coordinating 8+ character words.",
        keys: [],
        content: "knowledge technical experience professional",
        tips: ["Don't let long words break your rhythm.", "Chunk them into syllables."],
        passingCriteria: { accuracy: 98, wpm: 60 },
        difficulty: 7,
        target_wpm: 80
    },
    {
        id: 62,
        title: "Long Words II: Expansion",
        phase: 4,
        description: "Building stamina with complexity.",
        keys: [],
        content: "application infrastructure environment development",
        tips: ["Stay relaxed through the entire word.", "Maintain center anchors."],
        passingCriteria: { accuracy: 98, wpm: 60 },
        difficulty: 8,
        target_wpm: 85
    },
    {
        id: 63,
        title: "Common Phrases II",
        phase: 4,
        description: "Mastering the top 100 word combinations.",
        keys: [],
        content: "in order to as long as for example to be able to",
        tips: ["These should feel like single units of thought.", "Flow through them."],
        passingCriteria: { accuracy: 99, wpm: 75 },
        difficulty: 7,
        target_wpm: 90
    },
    {
        id: 64,
        title: "Technical Vocabulary",
        phase: 4,
        description: "Software and hardware terms.",
        keys: [],
        content: "software hardware firmware network database",
        tips: ["Precision on technical jargon.", "Maintain high speed."],
        passingCriteria: { accuracy: 99, wpm: 80 },
        difficulty: 8,
        target_wpm: 95
    },
    {
        id: 65,
        title: "Accuracy Master II",
        isMasterMode: true,
        phase: 4,
        description: "Perfect flow challenge.",
        keys: [],
        content: "A single mistake is the difference between pro and elite.",
        tips: ["No errors allowed.", "Reset on mistake."],
        passingCriteria: { accuracy: 100, wpm: 60 },
        difficulty: 10,
        target_wpm: 75
    },
    {
        id: 66,
        title: "Burst: Common Endings",
        type: 'burst',
        phase: 4,
        description: "Max speed on -able, -ment, -ness.",
        keys: [],
        content: "able able able ment ment ment ness ness ness",
        tips: ["raw twitch coordination.", "Build max speed on suffixes."],
        passingCriteria: { accuracy: 90, wpm: 100 },
        difficulty: 9,
        target_wpm: 120
    },
    {
        id: 67,
        title: "Punctuation Flow",
        phase: 4,
        description: "Integrating symbols into dense text.",
        keys: [],
        content: "The price was $10.99; we paid via credit card (Visa).",
        tips: ["Mixing numbers, symbols, and capitals.", "Stay predictable."],
        passingCriteria: { accuracy: 98, wpm: 70 },
        difficulty: 9,
        target_wpm: 85
    },
    {
        id: 68,
        title: "Metronome: 90 BPM",
        phase: 4,
        description: "High-speed rhythm sync.",
        keys: [],
        content: "The rhythm of the keys is the rhythm of your mind.",
        tips: ["Keep up with the pulse.", "Don't fall behind."],
        passingCriteria: { accuracy: 99, wpm: 90 },
        difficulty: 9,
        target_wpm: 90
    },
    {
        id: 69,
        title: "Quote Mastery I",
        phase: 4,
        description: "Famous literary quotes.",
        keys: [],
        content: "To be, or not to be, that is the question.",
        tips: ["Incorporate commas and flow.", "Classic literature rhythm."],
        passingCriteria: { accuracy: 99, wpm: 80 },
        difficulty: 8,
        target_wpm: 100
    },
    {
        id: 70,
        title: "The 'TION' Master Class",
        phase: 4,
        description: "Advanced ending speed.",
        keys: [],
        content: "communication information imagination preparation",
        tips: ["Mastering the transition into -tion.", "Right hand flow focus."],
        passingCriteria: { accuracy: 99, wpm: 85 },
        difficulty: 8,
        target_wpm: 105
    },
    {
        id: 71,
        title: "Speed Sprint: Bottom Row",
        type: 'burst',
        phase: 4,
        description: "Max speed on the difficult row.",
        keys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/'],
        content: "zxcv bnm,. / cvb nm / zx cv m, .",
        tips: ["Coordinate your index and middle fingers.", "Stay fast."],
        passingCriteria: { accuracy: 90, wpm: 80 },
        difficulty: 10,
        target_wpm: 100
    },
    {
        id: 72,
        title: "Elite Trigraph: ION",
        phase: 4,
        description: "Finger coordination drill.",
        keys: [],
        content: "ion ion ion ion ion ion ion ion ion ion",
        tips: ["Vertical right hand movement.", "Super fast snap."],
        passingCriteria: { accuracy: 100, wpm: 100 },
        difficulty: 7,
        target_wpm: 120
    },
    {
        id: 73,
        title: "Flow State Training I",
        phase: 4,
        description: "5-minute endurance test.",
        keys: [],
        content: "The flow state is where time disappears and speed is effortless.",
        tips: ["Maintain focus for the entire duration.", "Don't drop accuracy."],
        passingCriteria: { accuracy: 99, wpm: 90 },
        difficulty: 8,
        target_wpm: 110
    },
    {
        id: 74,
        title: "Blind Spot Check",
        phase: 4,
        description: "Training your weakest fingers.",
        keys: ['z', 'x', 'q', 'p', 'Shift'],
        content: "Quell Zion Extra Prize Quiet Zone Xray",
        tips: ["Pinky and ring finger focus.", "Outer reaches drill."],
        passingCriteria: { accuracy: 98, wpm: 70 },
        difficulty: 9,
        target_wpm: 85
    },
    {
        id: 75,
        title: "Pacing Drill: 100 WPM",
        phase: 4,
        description: "Hitting the triple-digit benchmark.",
        keys: [],
        content: "One hundred words per minute is the mark of a true typist.",
        tips: ["Maintain a perfectly steady 100 WPM rate.", "Zero variance."],
        passingCriteria: { accuracy: 100, wpm: 100 },
        difficulty: 9,
        target_wpm: 105
    },
    {
        id: 76,
        title: "Code Proficiency: Basic HTML",
        phase: 4,
        description: "Real-world tech writing.",
        keys: [],
        content: "<div id=\"main\"><p>Hello World</p></div>",
        tips: ["Closing tags and quotes.", "Stay fast on the angle brackets."],
        passingCriteria: { accuracy: 98, wpm: 80 },
        difficulty: 8,
        target_wpm: 100
    },
    {
        id: 77,
        title: "Code Proficiency: Simple CSS",
        phase: 4,
        description: "Styling syntax speed.",
        keys: [],
        content: ".body { margin: 0; padding: 20px; color: #fff; }",
        tips: ["Colons, semicolons, and braces.", "Steady flow through symbols."],
        passingCriteria: { accuracy: 98, wpm: 80 },
        difficulty: 9,
        target_wpm: 100
    },
    {
        id: 78,
        title: "Technical Review",
        phase: 4,
        description: "Reviewing all Proficiency skills.",
        keys: [],
        content: "Pro-typing involves mixing complex text with high accuracy.",
        tips: ["Stay present.", "Breathe through the difficult words."],
        passingCriteria: { accuracy: 99.5, wpm: 90 },
        difficulty: 9,
        target_wpm: 110
    },
    {
        id: 79,
        title: "Endurance Sprint",
        type: 'burst',
        phase: 4,
        description: "30-second max intensity.",
        keys: [],
        content: "go go go go go go go go go go go go go go",
        tips: ["Pure twitch coordination.", "Break your limits."],
        passingCriteria: { accuracy: 85, wpm: 140 },
        difficulty: 10,
        target_wpm: 160
    },
    {
        id: 80,
        title: "Proficiency Graduation",
        phase: 4,
        description: "End of Week 8 benchmark.",
        keys: [],
        content: "You have joined the top 1% of typists globally. Mastery awaits.",
        tips: ["Benchmark test.", "Must hit 100+ WPM with 99.5% accuracy."],
        passingCriteria: { accuracy: 99.5, wpm: 100 },
        difficulty: 10,
        target_wpm: 115
    },

    // --- PHASE 5: MASTERY (Lessons 81-100) ---
    // Goal: Complex Code, 110-135 WPM
    {
        id: 81,
        title: "Master Mode: Syntax II",
        isMasterMode: true,
        phase: 5,
        description: "Perfect professional code. No errors.",
        keys: [],
        content: "export default function App() { return <div />; }",
        tips: ["One mistake = Reset.", "Elite precision focus."],
        passingCriteria: { accuracy: 100, wpm: 80 },
        difficulty: 10,
        target_wpm: 100
    },
    {
        id: 82,
        title: "Difficult Combos: Symbols",
        phase: 5,
        description: "The 'Outer-Reach' nightmare.",
        keys: ['~', '`', '|', '\\', '{', '}'],
        content: "~~temp~~ { \\ o / } | ~ | `test`",
        tips: ["Rare but vital symbol reaches.", "Strengthen outer fingers."],
        passingCriteria: { accuracy: 97, wpm: 70 },
        difficulty: 10,
        target_wpm: 90
    },
    {
        id: 83,
        title: "Scientific Notation Speed",
        phase: 5,
        description: "Advanced math typing.",
        keys: ['e', '^', '*', '(', ')'],
        content: "6.022e23 * (1.5^-2); 3.14159 * r^2",
        tips: ["Complex symbol transitions.", "Keep your rhythm."],
        passingCriteria: { accuracy: 98, wpm: 75 },
        difficulty: 10,
        target_wpm: 95
    },
    {
        id: 84,
        title: "SQL Query Sprint",
        phase: 5,
        description: "Database language speed.",
        keys: [],
        content: "SELECT * FROM users WHERE active = 1 GROUP BY id;",
        tips: ["Uppercase keywords require shift/caps flow.", "Precision query end."],
        passingCriteria: { accuracy: 99, wpm: 90 },
        difficulty: 10,
        target_wpm: 110
    },
    {
        id: 85,
        title: "Bash Scripting Basics",
        phase: 5,
        description: "CLI and script syntax.",
        keys: ['$', '/', '#'],
        content: "#!/bin/bash\necho \"Update successful\"\nrm -rf /tmp/cache",
        tips: ["Forward and backward slashes.", "Dashes for flags."],
        passingCriteria: { accuracy: 98, wpm: 85 },
        difficulty: 10,
        target_wpm: 105
    },
    {
        id: 86,
        title: "Burst: Special Symbols",
        type: 'burst',
        phase: 5,
        description: "Max speed on symbols.",
        keys: ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')'],
        content: "!@#$% ^&*() !@#$% ^&*()",
        tips: ["raw twitch speed on shifted keys.", "Build max coordination."],
        passingCriteria: { accuracy: 90, wpm: 80 },
        difficulty: 10,
        target_wpm: 100
    },
    {
        id: 87,
        title: "Metronome: 120 BPM",
        phase: 5,
        description: "Elite rhythm sync.",
        keys: [],
        content: "The heart of an elite typist beats at 120 per minute.",
        tips: ["Two characters per beat or one? You decide.", "Stay in sync."],
        passingCriteria: { accuracy: 100, wpm: 120 },
        difficulty: 10,
        target_wpm: 120
    },
    {
        id: 88,
        title: "Markdown Documentation",
        phase: 5,
        description: "Formatting speed.",
        keys: [],
        content: "## Feature List\n- [x] Item 1\n- [ ] Item 2\n> Warning: Data loss!",
        tips: ["Mixing brackets and symbols.", "Fast list entry."],
        passingCriteria: { accuracy: 99, wpm: 100 },
        difficulty: 9,
        target_wpm: 120
    },
    {
        id: 89,
        title: "Async/Await Patterns",
        phase: 5,
        description: "Modern JS logic speed.",
        keys: [],
        content: "async function sync() { await doWork(); }",
        tips: ["Master the common logic keywords.", "Steady flow."],
        passingCriteria: { accuracy: 99, wpm: 100 },
        difficulty: 9,
        target_wpm: 125
    },
    {
        id: 90,
        title: "Object Mapping Sprint",
        phase: 5,
        description: "Key-value pair speed.",
        keys: [],
        content: "const data = { id: 1, type: 'pro', value: 95 };",
        tips: ["Precision on curly braces and colons.", "Fast property entry."],
        passingCriteria: { accuracy: 99, wpm: 110 },
        difficulty: 9,
        target_wpm: 130
    },
    {
        id: 91,
        title: "Elite Trigraph: OUS, ENT",
        phase: 5,
        description: "Focus on -ous and -ent endings.",
        keys: [],
        content: "famous nervous different current present",
        tips: ["High speed suffix chunks.", "Let it flow."],
        passingCriteria: { accuracy: 100, wpm: 120 },
        difficulty: 8,
        target_wpm: 140
    },
    {
        id: 92,
        title: "Elite Trigraph: ION, ICE",
        phase: 5,
        description: "Focus on -ion and -ice endings.",
        keys: [],
        content: "action notice price section justice office",
        tips: ["Right hand agility masterclass.", "Zero lag."],
        passingCriteria: { accuracy: 100, wpm: 125 },
        difficulty: 8,
        target_wpm: 145
    },
    {
        id: 93,
        title: "Regex Mastery: Patterns",
        phase: 5,
        description: "Pattern matching speed.",
        keys: [],
        content: "/^[a-zA-Z0-9]+$/ .test(input);",
        tips: ["Mixing all reaches and symbols.", "Total focus."],
        passingCriteria: { accuracy: 97, wpm: 80 },
        difficulty: 10,
        target_wpm: 100
    },
    {
        id: 94,
        title: "JSON Data Serialization",
        phase: 5,
        description: "Data transport format speed.",
        keys: [],
        content: "JSON.stringify({ user: 'dev', level: 110 });",
        tips: ["Quotes and nested objects.", "Fast capital JSON."],
        passingCriteria: { accuracy: 99, wpm: 100 },
        difficulty: 9,
        target_wpm: 120
    },
    {
        id: 95,
        title: "Accuracy Master III",
        isMasterMode: true,
        phase: 5,
        description: "Perfect professional flow.",
        keys: [],
        content: "To reach the top, you must eliminate every single distraction.",
        tips: ["Zero error tolerance.", "Breathe through the pressure."],
        passingCriteria: { accuracy: 100, wpm: 100 },
        difficulty: 10,
        target_wpm: 110
    },
    {
        id: 96,
        title: "Burst: Alpha-Numeric mix",
        type: 'burst',
        phase: 5,
        description: "Max speed on mixed input.",
        keys: [],
        content: "alpha1 beta2 gamma3 delta4 epsilon5",
        tips: ["Coordinate words and numbers.", "15-second explosion."],
        passingCriteria: { accuracy: 90, wpm: 110 },
        difficulty: 10,
        target_wpm: 130
    },
    {
        id: 97,
        title: "Logical Operators: Elite",
        phase: 5,
        description: "Complex logic symbol flow.",
        keys: [],
        content: "if (x && !y || z === 10) { proceed(); }",
        tips: ["Mixing logic and brackets.", "Stay snappy."],
        passingCriteria: { accuracy: 98, wpm: 100 },
        difficulty: 10,
        target_wpm: 120
    },
    {
        id: 98,
        title: "Mastery Review",
        phase: 5,
        description: "Consolidating all Mastery skills.",
        keys: [],
        content: "The elite typist treats code and text with equal precision.",
        tips: ["Final review of Week 10.", "Breathe and flow."],
        passingCriteria: { accuracy: 99.5, wpm: 115 },
        difficulty: 10,
        target_wpm: 130
    },
    {
        id: 99,
        title: "Endurance Test: 10 Minutes",
        phase: 5,
        description: "The long-distance marathon.",
        keys: [],
        content: "Endurance is the ultimate differentiator in the professional world.",
        tips: ["Keep your stamina high.", "Don't let fatigue lower your accuracy."],
        passingCriteria: { accuracy: 99.5, wpm: 110 },
        difficulty: 10,
        target_wpm: 125
    },
    {
        id: 100,
        title: "Mastery Graduation",
        phase: 5,
        description: "End of Week 10 benchmark.",
        keys: [],
        content: "You are a master of the digital keys. Only the Elite remains.",
        tips: ["Milestone benchmark.", "Must hit 120+ WPM with 99.8% accuracy."],
        passingCriteria: { accuracy: 99.8, wpm: 120 },
        difficulty: 10,
        target_wpm: 135
    },

    // --- PHASE 6: ELITE (Lessons 101-110) ---
    // Goal: 150+ WPM, Professional Excellence
    {
        id: 101,
        title: "Elite Pacing: 140 WPM",
        phase: 6,
        description: "Holding the steady line of speed.",
        keys: [],
        content: "Success at this speed requires absolute mental focus and calm.",
        tips: ["Zero variance allowable.", "Be the machine."],
        passingCriteria: { accuracy: 100, wpm: 140 },
        difficulty: 10,
        target_wpm: 145
    },
    {
        id: 102,
        title: "Master Mode: Full Block",
        isMasterMode: true,
        phase: 6,
        description: "Perfect elite paragraph.",
        keys: [],
        content: "If you want to be elite, you must practice the impossible daily.",
        tips: ["Zero errors.", "Ultimate test."],
        passingCriteria: { accuracy: 100, wpm: 120 },
        difficulty: 10,
        target_wpm: 130
    },
    {
        id: 103,
        title: "Elite Code: Frameworks",
        phase: 6,
        description: "High-speed React/TS syntax.",
        keys: [],
        content: "const [state, setState] = useState<T>(init);",
        tips: ["Angle brackets and state hooks.", "Propping up the web."],
        passingCriteria: { accuracy: 99.5, wpm: 110 },
        difficulty: 10,
        target_wpm: 125
    },
    {
        id: 104,
        title: "Elite Code: Backend",
        phase: 6,
        description: "Database and API speed.",
        keys: [],
        content: "await db.collection('v1').find({ id: req.params.id });",
        tips: ["Method chaining and nesting.", "Fast backend entry."],
        passingCriteria: { accuracy: 99.5, wpm: 110 },
        difficulty: 10,
        target_wpm: 125
    },
    {
        id: 105,
        title: "Elite Sprint: Pangram bank",
        type: 'burst',
        phase: 6,
        description: "Max speed on all letters.",
        keys: [],
        content: "the quick brown fox jumps over the lazy dog",
        tips: ["Coordinate all reaches.", "15-second total sprint."],
        passingCriteria: { accuracy: 95, wpm: 160 },
        difficulty: 10,
        target_wpm: 180
    },
    {
        id: 106,
        title: "Metronome: 150 BPM",
        phase: 6,
        description: "The sound barrier sync.",
        keys: [],
        content: "The extreme rhythm of elite performance is achieved now.",
        tips: ["Unbelievable speed sync.", "Absolute focus."],
        passingCriteria: { accuracy: 100, wpm: 150 },
        difficulty: 10,
        target_wpm: 150
    },
    {
        id: 107,
        title: "Elite Suffix: MASTER",
        phase: 6,
        description: "Focus on -fully, -ward, -wise.",
        keys: [],
        content: "beautifully backward clockwise successful",
        tips: ["Uncommon but fast suffixes.", "Maintain flow."],
        passingCriteria: { accuracy: 100, wpm: 140 },
        difficulty: 9,
        target_wpm: 155
    },
    {
        id: 108,
        title: "The God of Flow I",
        phase: 6,
        description: "10-minute 130+ WPM endurance.",
        keys: [],
        content: "To type at the speed of thought is to join the elite gods of flow.",
        tips: ["Don't fade.", "Maintain the elite pace."],
        passingCriteria: { accuracy: 99.8, wpm: 130 },
        difficulty: 10,
        target_wpm: 145
    },
    {
        id: 109,
        title: "The God of Flow II",
        phase: 6,
        description: "The final barrier.",
        keys: [],
        content: "One hundred and fifty words per minute is now within your reach.",
        tips: ["Unbelievable speed ceiling.", "Give it everything."],
        passingCriteria: { accuracy: 99.8, wpm: 145 },
        difficulty: 10,
        target_wpm: 160
    },
    {
        id: 110,
        title: "LEGEND FINALE (150+ WPM)",
        phase: 6,
        description: "The Mastery Journey ends here.",
        keys: [],
        content: "You are the Legend. One with the machine. 150 WPM achieved.",
        tips: ["The finale of the 110-lesson Mastery Course.", "You are the God of Flow."],
        passingCriteria: { accuracy: 99.9, wpm: 155 },
        difficulty: 10,
        target_wpm: 175
    }
];
